In [ ]:
"""Date and time."""

In [2]:
import datetime
from datetime import datetime, timedelta

import pandas as pd
import pytz

In [23]:
print(datetime.datetime.now())

2026-07-31 17:25:40.809613

In [24]:
print(datetime.now())

2026-07-31 17:26:23.484882

In [25]:
cur_dt = datetime.now()
print(cur_dt)

2026-07-31 17:27:40.920614

In [26]:
print(
    cur_dt.year,
    cur_dt.month,
    cur_dt.day,
    cur_dt.hour,
    cur_dt.minute,
    cur_dt.second,
    cur_dt.microsecond,
)

2026 7 31 17 27 40 920614

In [27]:
print(cur_dt.weekday(), cur_dt.isoweekday())

4 5

In [28]:
print(cur_dt.tzinfo)

None

In [34]:
dt_moscow = datetime.now(pytz.timezone("Europe/Moscow"))
print(dt_moscow)

2026-07-31 17:55:02.061898+03:00

In [35]:
print(dt_moscow.tzinfo)

Europe/Moscow

In [46]:
timestamp = datetime.now().timestamp()
print(timestamp)

1785509812.59897

In [47]:
print(datetime.fromtimestamp(timestamp))

2026-07-31 17:56:52.598970

In [48]:
hb = datetime(1991, 2, 20)
print(hb)

1991-02-20 00:00:00

In [49]:
print(hb.year)

1991

In [52]:
print(datetime.timestamp(hb))

666997200.0

In [54]:
str_to_dt = "2007-12-02 12:30:45"
type(str_to_dt)

str

In [55]:
res_dt = datetime.strptime(str_to_dt, "%Y-%m-%d %H:%M:%S")

print(res_dt)
print(type(res_dt))

2007-12-02 12:30:45
<class 'datetime.datetime'>

In [56]:
dt_to_str = datetime(2002, 11, 19)
type(dt_to_str)

datetime.datetime

In [57]:
res_str = datetime.strftime(dt_to_str, "%A, %B %d, %Y")

print(res_str)
print(type(res_str))

Tuesday, November 19, 2002
<class 'str'>

In [58]:
date1 = datetime(1905, 6, 30)
date2 = datetime(1916, 5, 11)

In [59]:
date1 < date2

True

In [60]:
date1 > date2

False

In [61]:
"2007-12-02" > "2002-11-19"

True

In [62]:
datetime(2007, 12, 2) > datetime(2002, 11, 19)

True

In [63]:
diff = date2 - date1
print(diff)

3968 days, 0:00:00

In [64]:
type(diff)

datetime.timedelta

In [65]:
print(diff.days)

3968

In [67]:
timedelta(days=1)

datetime.timedelta(days=1)

In [68]:
future = datetime(2070, 1, 1)
future

datetime.datetime(2070, 1, 1, 0, 0)

In [69]:
time_travel = timedelta(days=365) * 170

past = future - time_travel

past

datetime.datetime(1900, 2, 12, 0, 0)

In [70]:
datetime(2070, 1, 1) - datetime(1900, 1, 1)

datetime.timedelta(days=62092)

In [71]:
time_travel = timedelta(days=62092)

past = future - time_travel
past

datetime.datetime(1900, 1, 1, 0, 0)

In [72]:
365 * 170

62050

In [73]:
datetime(2070, 1, 1) - datetime(1900, 1, 1)

datetime.timedelta(days=62092)

In [74]:
cur_date = datetime(2021, 1, 1)
end_date = datetime(2021, 1, 10)

while cur_date <= end_date:

    print(cur_date.strftime("%b %d, %Y"))

    cur_date += timedelta(days=1)

Jan 01, 2021
Jan 02, 2021
Jan 03, 2021
Jan 04, 2021
Jan 05, 2021
Jan 06, 2021
Jan 07, 2021
Jan 08, 2021
Jan 09, 2021
Jan 10, 2021

In [75]:
numbers = ["5", "10", "a", "15", "10"]

total = 0

for number in numbers:

    try:
        total += int(number)
    except:
        pass

total

40

In [76]:
total = 0

for number in numbers:
    try:
        total += int(number)
    except:
        print(f"Элемент '{number}' обработать не удалось")

total

Элемент 'a' обработать не удалось

40

In [77]:
temp = pd.read_csv("temperature.csv")
temp

          Date  Temp
0   2002-01-01  47.1
1      2002-02  50.5
2    2002-03-1  54.9
3      2002-04  66.1
4   2002-05-01  72.7
5      2002-06  83.2
6      2002-07  88.8
7    2002-08-1  87.8
8   2002-09-01  80.2
9   2002-10-01  64.1
10     11-2002  53.9
11  2002-12-01  44.1

In [79]:
formats = ["%Y-%m-%d", "%Y-%m-%-d", "%Y-%m"]

counter = 0

for d in temp.Date:

    for format in formats:

        try:
            print(datetime.strptime(d, format))
            counter += 1

        except:

            pass


print("Не обработалось записей:", len(temp) - counter)

2002-01-01 00:00:00
2002-02-01 00:00:00
2002-03-01 00:00:00
2002-04-01 00:00:00
2002-05-01 00:00:00
2002-06-01 00:00:00
2002-07-01 00:00:00
2002-08-01 00:00:00
2002-09-01 00:00:00
2002-10-01 00:00:00
2002-12-01 00:00:00
Не обработалось записей: 1

In [80]:
temp_parsed = pd.read_csv("temperature.csv", index_col="Date", parse_dates=True)
temp_parsed

            Temp
Date
2002-01-01  47.1
2002-02     50.5
2002-03-1   54.9
2002-04     66.1
2002-05-01  72.7
2002-06     83.2
2002-07     88.8
2002-08-1   87.8
2002-09-01  80.2
2002-10-01  64.1
11-2002     53.9
2002-12-01  44.1

In [81]:
type(temp_parsed.index)

pandas.Index